In [1]:
import sys
import mysql.connector

import sqlalchemy
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import os
import plotly.express as px

### Leemos los datos desde un excel

In [2]:
df_2018 = pd.read_excel('hotel_revenue_historical_full.xlsx', sheet_name='2018')
df_2019 = pd.read_excel('hotel_revenue_historical_full.xlsx', sheet_name='2019')
df_2020 = pd.read_excel('hotel_revenue_historical_full.xlsx', sheet_name='2020')
df_meal_cost = pd.read_excel('hotel_revenue_historical_full.xlsx', sheet_name='meal_cost')
df_market_segment = pd.read_excel('hotel_revenue_historical_full.xlsx', sheet_name='market_segment')

In [12]:
df_hotel_revenue = pd.concat([df_2018, df_2019], ignore_index = True)
df_hotel_revenue = pd.concat([df_hotel_revenue, df_2020], ignore_index = True)

In [14]:
dic_month = {'January':'01', 'February':'02', 'March':'03', 'April':'04', 'May':'05', 
             'June':'06','July':'07', 'August':'08', 'September':'09', 'October':'10', 
             'November':'11', 'December':'12'}
df_hotel_revenue['arrival_date_month'] = df_hotel_revenue['arrival_date_month'].replace(dic_month)

In [19]:
df_hotel_revenue['arrival_date_day_of_month'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31], dtype=int64)

In [21]:
df_hotel_revenue['arrival_date'] = df_hotel_revenue[['arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month']].apply(lambda x: str(x[0]) + '-' + x[1] + '-' + str(x[2]).zfill(2), axis = 1)

In [ ]:
### ¿cómo se comporta el revenue a lo largo de los años, o de los días?
### ¿deberíamos incrementar el tamaño de los estacionamientos?
### ¿Qué tendencias se puede observar en los datos?
### - Revenue
### - Tarifa promedio diaria
### - Espacios disponibles/ocupados de los estacionamientos

In [32]:
#df_hotel_revenue = df_hotel_revenue.merge(df_market_segment, on = 'market_segment', how = 'left')
df_hotel_revenue = df_hotel_revenue.merge(df_meal_cost, on = 'meal', how = 'left')

In [35]:
df_hotel_revenue['revenue'] = (df_hotel_revenue['stays_in_week_nights'] + df_hotel_revenue['stays_in_weekend_nights'])*df_hotel_revenue['adr']*(1- df_hotel_revenue['Discount'])

In [48]:
print('Revenue (en Millones):',df_hotel_revenue['revenue'].sum()/1000000)

revenue_year = df_hotel_revenue.groupby(['arrival_date_year'],as_index=False)['revenue'].sum()
revenue_hotel = df_hotel_revenue.groupby(['arrival_date_year','hotel'],as_index=False)['revenue'].sum()

Revenue (en Millones): 37.3440786475

In [45]:
df_hotel_revenue.groupby(['arrival_date_year'],as_index=False)['arrival_date'].max()

   arrival_date_year arrival_date
0               2018   2018-12-31
1               2019   2019-12-31
2               2020   2020-08-31

In [42]:
fig = px.bar(revenue_year, x = 'arrival_date_year', y = 'revenue', height = 400)
fig

In [50]:
fig = px.bar(revenue_hotel, x = 'arrival_date_year', y = 'revenue', color = 'hotel', height = 400, barmode = 'group')
fig

In [55]:
columns_to_show = ['hotel', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'country', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'arrival_date','Discount', 'revenue']

df_hotel_final = df_hotel_revenue[columns_to_show]

### Construimos base de datos

In [57]:
## Conexion con el servidor
conexion = mysql.connector.connect(
    user = user,
    password = password, ## Añadir password
    host = host,
)

## Creamos un cursor 
cursor = conexion.cursor()

## Creamos la base de datos
try:
    cursor.execute("CREATE DATABASE hotel;")
    print("Se creó correctamente la base de datos.")
except:
    print("Ocurrió un error al crear la base de datos. Inténtelo de nuevo.")
finally:
    cursor.close()
    conexion.close()
    print("Conexión cerrada exitosamente")

Se creó correctamente la base de datos.
Conexión cerrada exitosamente

In [58]:
### Creamos la tabla

#engine = sqlalchemy.create_engine("mysql+pymysql://user:password@host:puerto/database_name")
engine = sqlalchemy.create_engine("mysql+pymysql://root:@localhost:3306/hotel")

141947

In [61]:
df_hotel_final.head(4)

,hotel,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,country,adr,required_car_parking_spaces,total_of_special_requests,arrival_date,Discount,revenue
0,Resort Hotel,2018,07,27,1,0,3,PRT,82.0,0,1,2018-07-01,0.3,172.20
1,Resort Hotel,2018,07,27,1,0,3,PRT,105.5,0,0,2018-07-01,0.3,221.55
2,Resort Hotel,2018,07,27,1,0,4,PRT,123.0,0,0,2018-07-01,0.3,344.40
3,Resort Hotel,2018,07,27,1,2,5,PRT,107.0,0,2,2018-07-01,0.3,524.30

In [64]:
### Crear tabla
df_hotel_final.head(10).to_sql(
    name = 'hotel_revenue3',
    con = engine,
    index = True
)

10

In [59]:
df = pd.read_sql(
    'hotel_revenue',
    con = engine,
)

In [60]:
df.head(5)

,hotel,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,country,adr,required_car_parking_spaces,total_of_special_requests,arrival_date,Discount,revenue
0,Resort Hotel,2018,07,27,1,0,3,PRT,82.0,0,1,2018-07-01,0.3,172.20
1,Resort Hotel,2018,07,27,1,0,3,PRT,105.5,0,0,2018-07-01,0.3,221.55
2,Resort Hotel,2018,07,27,1,0,4,PRT,123.0,0,0,2018-07-01,0.3,344.40
3,Resort Hotel,2018,07,27,1,2,5,PRT,107.0,0,2,2018-07-01,0.3,524.30
4,Resort Hotel,2018,07,27,1,2,8,PRT,108.3,0,2,2018-07-01,0.1,974.70